### PR TITLE
Tokendings errorhandling

### LINKED ISSUE #29: Tokenutveksling feilhåndtering
- [x] Azure
- [x] Tokending

Feil i tokenutveksling er ikke håndter godt nok. Børe se på å kaste egne exceptions med mer info.

### PR DESCRIPTION
**Pull request by rannveigskjerve**
Closes #29

### CODE REVIEW

File: azure-exchange/src/main/kotlin/no/nav/tms/token/support/azure/exchange/service/NonCachingTokendingsService.kt [hunk 1]
```diff
@@ -54,3 +61,16 @@ class CachingAzureService internal constructor(
         return AccessTokenEntry.fromResponse(response)
     }
 }
+
+class AzureExchangeException(val originalThrowable: Throwable, targetApp: String) :
+    Exception() {
+
+    val stackTraceSummary =
+        originalThrowable.stackTrace.firstOrNull()?.let { stacktraceElement ->
+            """    Tokendingsexchange feiler for $targetApp
```
Comment (chris-santa) [inline azure-exchange/src/main/kotlin/no/nav/tms/token/support/azure/exchange/service/NonCachingTokendingsService.kt]: Tokendings -> azure

**Review by chris-santa — APPROVED** [review]
